name: ci

on:
  push:
  pull_request:

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        os: ['macOS-latest', 'ubuntu-18.04']
        tfp: ['0.11']
        include:
          - os: ubuntu-18.04
            cran: https://demo.rstudiopm.com/all/__linux__/bionic/latest
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (TFP ${{ matrix.tfp }}, TF ${{matrix.tf}})

    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: install dependencies
        run: Rscript -e "install.packages('remotes')" -e "remotes::install_deps(dependencies = TRUE)" -e "remotes::install_cran('rcmdcheck')"
      - name: check
        continue-on-error: ${{ contains(matrix.allow_failure, 'true') }}
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'warning', check_dir = 'check')"
      - name: coverage
        continue-on-error: true
        run: |
          tar -C .. -xf $PKG_TARBALL
          Rscript -e 'covr::codecov()'
          Rscript -e 'lintr::lint_package()'
